trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# download the secure publish profile file
- task: DownloadSecureFile@1
  name: pf
  inputs:
    secureFile: 'MovieShopVictorR.PublishSettings'  

# deploy using Publish Profile mode
- task: AzureWebApp@1
  displayName: Deploy to Azure App Service
  inputs:
    connectionType: 'PublishProfile'
    publishProfile: '$(pf.secureFilePath)'          
    appName: 'MovieShopVictorR'                     
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

# optional
- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
