trigger:
- main

pool:
  name: Default   # self-hosted agent

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true


- task: AzureWebApp@1
  displayName: Deploy to Azure App Service
  inputs:
    connectionType: 'PublishProfile'
    publishProfile: '$(publishProfileSecret)'   
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

# Optional: keep artifact
- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
