trigger:
- main

pool:
  name: Default   

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# Debug: make sure a .zip exists where we expect it
- script: |
    echo "Publish dir: $(Build.ArtifactStagingDirectory)"
    ls -la $(Build.ArtifactStagingDirectory)
  displayName: 'List publish output (debug)'

- task: AzureWebApp@1
  displayName: Deploy to Azure App Service
  inputs:
    connectionType: 'PublishProfile'
    publishProfile: '$(PUBLISH_PROFILE)'         
    appName: 'MovieShopVictorR'                 
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

# (optional) keep the artifact
- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
